# Generated by Django 3.2.9 on 2021-11-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_forum_forumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='tag',
            field=models.CharField(default='', max_length=5),
        ),
    ]
