# Generated by Django 3.2.9 on 2021-11-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0003_forum_tag'),
        ('fms', '0004_auto_20211102_1801'),
    ]

    operations = [
    ]
