# Generated by Django 3.2.9 on 2021-11-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0005_merge_0003_forum_tag_0004_auto_20211102_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
