# Generated by Django 3.2.9 on 2021-11-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0008_profilebio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentUser',
        ),
    ]
